server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.mvc: DEBUG
    org.springframework.web.servlet: DEBUG

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: profile-service
              uri: lb://profileservice
              predicates:
                - Path=/api/v1/profiles,/api/v1/profiles/**
            - id: post-service
              uri: lb://postservice
              predicates:
                - Path=/api/v1/posts,/api/v1/posts/**

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/